# Generated by Django 5.1.6 on 2025-03-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
