# Generated by Django 5.1.6 on 2025-03-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_accountrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountRequest',
        ),
    ]
